[build]
  publish = "."

# Proxy Kalshi API calls
[[redirects]]
  from = "/api/*"
  to = "http://209.38.37.63:5000/api/:splat"
  status = 200
  force = true

# Proxy Polymarket API calls
[[redirects]]
  from = "/poly-api/*"
  to = "http://134.122.86.195:8081/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
