[build]
  publish = "."

# Proxy API calls to the backend server
[[redirects]]
  from = "/api/*"
  to = "http://138.197.212.247:8080/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
